### ISSUE TITLE
Team Management Tools

### ISSUE THREAD

**Issue by Clxiu** [Clxiu/Trust-Indicator#10]
## Description
Decide the tools for team management

## Why
Project management.

## Closing Criteria

- [x] Setup team management tools
- [x] Decision log

**Comment by Clxiu** [comment]
Added [decision log](https://github.com/Clxiu/Trust-Indicator/blob/main/docs/Decision%20Logs/Tools%20for%20Project%20Management.md)

**Comment by Clxiu** [comment]
@YifangMeng Review plz. Thanks

**Comment by YifangMeng** [comment]
Done!
