### ISSUE TITLE
PROJECT: Update landing page

### ISSUE THREAD

**Issue by Clxiu** [Clxiu/Trust-Indicator#3]
## Description
Update the landing page on GitHub.

## Close Criteria
- [x] Update the landing page on GitHub.

**Comment by Clxiu** [comment]
- [x] Uploaded project files
- [x] Edited README.md
- [x] Checked link availability 
- [x] Added new team meeting, tutorial meeting and decision-making log
- [x] Keep old documents separate
- [ ] Add deliverables to README.md

**Comment by tonypioneer** [comment]
Close as completed.
